### ISSUE TITLE
简洁高效，用着不错！

### ISSUE THREAD

**Issue by Shuo-Jia** [xs9627/feedpop#1]
特地从应用商店过来！不知道是不是国内网络的问题，导致一些“官方”的RSS阅读器，同步特别慢，找了好久碰上了这个！不知道作者还在更新不，特地过来评论一下：
简洁高效，不过希望添加两个功能：
1、直接点击标记“已阅读”，而不是每次都得点击进去！
2、增加一个所有订阅主题的阅读栏，显示所有已经更新，这样直接在这个菜单栏就可以看所有的未阅读了！

**Comment by xs9627** [comment]
> 特地从应用商店过来！不知道是不是国内网络的问题，导致一些“官方”的RSS阅读器，同步特别慢，找了好久碰上了这个！不知道作者还在更新不，特地过来评论一下：
> 简洁高效，不过希望添加两个功能：
> 1、直接点击标记“已阅读”，而不是每次都得点击进去！
> 2、增加一个所有订阅主题的阅读栏，显示所有已经更新，这样直接在这个菜单栏就可以看所有的未阅读了！
感谢支持！下次更新会加入这两个功能。

**Comment by xs9627** [comment]
v1.0.3 版本加入了这两个功能。
commit 4092d052dba69aaf58d04a886d52a97a2408b76c
