### ISSUE TITLE
希望加入导入导出功能

### ISSUE THREAD

**Issue by zllfish** [xs9627/feedpop#10]
希望加入订阅链接的数据导出功能
这样重新安装系统以后 就只需要导入就可以了

**Comment by xs9627** [comment]
v1.1.1已经支持默认支持同步配置到Google Account，同步内容包含订阅的链接以及其他配置，重装系统登陆你的Google account之后会自动同步

**Comment by xs9627** [comment]
v1.1.2加入了导入导出到本地的功能，感谢你的建议！

**Comment by zllfish** [comment]
大佬太客气了
