### ISSUE TITLE
Links does not work well

### ISSUE THREAD

**Issue by melamoud** [xs9627/feedpop#139]
I created a link to audible RSS (list of new books) https://politepol.com/fd/xSv8BnG6dieh

see this code for example "<title>Critical Mass</title>
<link>https://www.audible.com/pd/Critical-Mass-Audiobook/177424361X?qid=1593433080&sr=1-1&ref=a_coming-so_c3_lProduct_1_1&pf_rd_p=a9e57c70-133b-49c9-be1f-14bcc1691149&pf_rd_r=KS4N7VR2FBNBC0EY1MPH</link>
"

The link is good, and if I use it from other feed it works well , but from your reader it browse to this link:
chrome-extension://nleicnolldoamnpiekcpifpimpolkelo/pd/Critical-Mass-Audiobook/177424361X?qid=1593433080&sr=1-1&ref=a_coming-so_c3_lProduct_1_1&pf_rd_p=a9e57c70-133b-49c9-be1f-14bcc1691149&pf_rd_r=KS4N7VR2FBNBC0EY1MPH

can you fix it ?

thanks

**Comment by xs9627** [comment]
Just played around on `https://politepol.com/` for a while, It's a cool site :)
I found all url in the feed content generated by `https://politepol.com/` are lack of the domain name, such as
```html
href="/pd/A-Beautifully-Foolish-Endeavor-Audiobook/059314631X?qid=1593433080&amp;sr=1-10&amp;ref=a_coming-so_c3_lProduct_1_10&amp;pf_rd_p=a9e57c70-133b-49c9-be1f-14bcc1691149&amp;pf_rd_r=KS4N7VR2FBNBC0EY1MPH"
```
It may caused by the url in the original site of `https://www.audible.com/` is the relative path. and I think the only way to make it works is to add the domain name to the url when opened. Will try some workaround to fix it.

**Comment by melamoud** [comment]
That’s for the quick response, 

 

I switched to a different extension that works well. But they have a different trick 

https://chrome.google.com/webstore/detail/feedbundle-online-rss-new/phpkhhdfcdlkcmakbfieencikecnddck

 

thanks

**Comment by xs9627** [comment]
Thanks for the info!
BTW, before the fix, (if you missed it) you could try the 'Open in new tab' button in the top right corner.
<img width="322" alt="Screen Shot 2020-06-29 at 10 10 17 PM" src="https://user-images.githubusercontent.com/7506756/86016633-9ef40480-ba55-11ea-96a5-07312b07d0e0.png">

**Comment by xs9627** [comment]
Will be contained in next release.
