### ISSUE TITLE
Suggestion: Import/Export OPML

### ISSUE THREAD

**Issue by drkui** [xs9627/feedpop#149]
A few improvements I could see on the import/export side is supporting .opml import/export. This would make it easier for new users to use your extension, especially if they have a bunch of feeds on another reader with OPML support (most do).

Which brings me to another thing, that is to support adding more than one link. It's currently like this now:
![image](https://user-images.githubusercontent.com/11448650/87750418-41c7b500-c7b0-11ea-8c59-20ed4ffd91d8.png)

However that only allows one RSS feed at a time. If I needed to import 100 feeds, I would much rather prefer a textbox where I can just copy/paste a bunch of links (one feed per line), click the add button, and be done.

**Comment by xs9627** [comment]
Will work on the .opml import/export. Thanks!

**Comment by xs9627** [comment]
Import/Export OPML will be added in Setting -> Backup & Restore

<img width="378" alt="Screen Shot 2020-07-23 at 1 34 26 PM" src="https://user-images.githubusercontent.com/7506756/88254950-7cb67500-cce9-11ea-95ec-d7bb601dde4d.png">

**Comment by xs9627** [comment]
Release Import/Export OPML feature with v1.2.4. Close this issue for now.
