### ISSUE TITLE
[Feature Request] Clean Cache when refresh / auto-refresh

### ISSUE THREAD

**Issue by foris323** [xs9627/feedpop#19]
Hi,
FeedPop is a really great RSS reader, it is what I need.
However I need some extra features, I want to auto clean the cache when auto execute the auto-refresh.
Is it possible to provide a option "Clean Cache when refresh" ?
Thanks a lot!

**Comment by foris323** [comment]
您好，
找了很久好用的 RSS reader，FeedPop 真的簡潔好用
我很需要自動清理緩存，希望能增加當 auto-refresh 的時候順便清理緩存的選項
感謝！

**Comment by xs9627** [comment]
请问自动清理缓存指的是定时执行现有的“设置”->“清理缓存”功能吗？
现有的清理缓存功能会清理所有的文章，如果定时执行的话也会把当天未读的文章清理掉，这样就会收不到新的更新。
“设置”里的“源订阅文章数”最小可以调到20，这样也不会占用太多缓存，符合你的需求吗？

**Comment by xs9627** [comment]
或者可不可以增加类似“清理已读文章”的选项，在执行refresh的时候自动清理已读的文章？

**Comment by foris323** [comment]
> 现有的清理缓存功能会清理所有的文章，如果定时执行的话也会把当天未读的文章清理掉，这样就会收不到新的更新。

請問把当天未读的文章清理掉，再去重新query當天的，這樣不會收到更新嗎？

其實我的主要問題是，我拿這個工具來做工作管理系統的訂閱
比如我有兩個源，"To do Tasks", "Resolved Tasks"
當任務完成後，任務會從 "To do Tasks" 移到 "Resolved Tasks"
但是我 local 訂閱的 "To do Tasks" 卻會持續顯示這個任務，清不掉 (源裡面已經沒這個任務)
所以才想讓每次重新query源的時候，把local清掉

**Comment by xs9627** [comment]
明白了，你的意思是本地的内容和源的内容保持同步，不管已读会未读，是吧？请问这样未读的内容同步后也希望清理吗？

**Comment by foris323** [comment]
您好，是的
1. 本地的內容跟源的內容保持同步，不管本地的內容是不是已讀
2. 同步後本地內容的已讀/未讀狀態不變
這兩個才是主要目的，清理就不用了，本來我是想透過清理達成 1
十分感謝

**Comment by xs9627** [comment]
1.1.4 release 包含了该功能，更新后可以通过关闭“设置” -> “保留历史内容”选项使本地内容和源内容保持同步。
